apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-aggregator
  namespace: streamflow-processing
spec:
  image: flink:1.20-java17
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.checkpoints.dir: file:///opt/flink/checkpoints
    execution.checkpointing.interval: "30000"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "512Mi"
      cpu: 0.1
  taskManager:
    resource:
      memory: "512Mi"
      cpu: 0.2
    replicas: 1
  job:
    jarURI: local:///opt/flink/usrlib/streamflow-jobs.jar
    entryClass: org.apache.flink.client.python.PythonDriver
    args:
      - "-py"
      - "/opt/flink/usrlib/realtime_aggregator.py"
    parallelism: 1
    upgradeMode: stateless
